# Generated by Django 4.2.2 on 2023-11-15 00:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Founder', 'Founder'), ('Admin', 'Admin'), ('Trainer', 'Trainer'), ('Subscriber', 'Subscriber')], max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to=accounts.models.profile_avatar_upload_to),
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roles', to='accounts.roles'),
        ),
    ]
