# Generated by Django 4.2.2 on 2023-12-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_roles_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
