# Generated by Django 4.2.2 on 2023-12-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_discord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(blank=True, choices=[('Founder', 'Founder'), ('Admin', 'Admin')], max_length=150, null=True),
        ),
    ]
