# Generated by Django 4.2.2 on 2024-02-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_restricted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roles',
        ),
        migrations.DeleteModel(
            name='AccountSettings',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
