# Generated by Django 4.2.2 on 2024-02-07 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_profile_restricted'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistWhitelistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('username', models.CharField(max_length=5000)),
                ('discord_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotCommands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=2000)),
                ('description', models.TextField()),
                ('working', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_opend', models.BooleanField(default=True)),
                ('bot_commands_opened', models.BooleanField(default=True)),
                ('bot_runing', models.BooleanField(blank=True, null=True)),
                ('bot_icon', models.CharField(blank=True, max_length=5000, null=True)),
                ('is_this_the_used_one', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField(blank=True, null=True)),
                ('guild_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guild_icon', models.CharField(blank=True, max_length=2000, null=True)),
                ('guild_owner_id', models.BigIntegerField(blank=True, null=True)),
                ('blacklist', models.BooleanField(default=False)),
                ('whitelist', models.BooleanField(default=False)),
                ('guild_blacklistusers', models.ManyToManyField(related_name='guild_blacklist_users', to='discordbot.blacklistwhitelistuser')),
                ('guild_whitelistusers', models.ManyToManyField(related_name='guild_whitelist_users', to='discordbot.blacklistwhitelistuser')),
            ],
        ),
        migrations.CreateModel(
            name='CoinsAcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.BigIntegerField(blank=True, default=0, null=True)),
                ('took_daily', models.BooleanField(default=False)),
                ('restricted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='blacklistwhitelistuser',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discordbot.guild'),
        ),
    ]
