# Generated by Django 4.2.2 on 2024-02-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklistwhitelistuser',
            name='guild',
        ),
        migrations.DeleteModel(
            name='BotCommands',
        ),
        migrations.DeleteModel(
            name='BotSettings',
        ),
        migrations.RemoveField(
            model_name='coinsacount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='blacklist',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='guild_blacklistusers',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='guild_whitelistusers',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='whitelist',
        ),
        migrations.DeleteModel(
            name='BlacklistWhitelistUser',
        ),
        migrations.DeleteModel(
            name='CoinsAcount',
        ),
    ]
